add possibility to prefix query with lang ":" params
CrackTC/rofi-ts pull request #1
Opened 2024-04-04 11:11 UTC by manuhabitela

:wave: hey, thanks a lot for this, very cool to have a rofi/translate-shell combo via a rofi mode instead of a whole separate script like other projects.

Here is a proposal that fits my usecase, figured it could be useful.

Since the whole input was passed to translate-shell as one param, there was no possibility to give from/to languages info.
This small patch allows us to specify lang now.

I'm not a C developer and I know just checking for ":" in first param is not that error-proof… Just figured I'd let you know!

Cheers,
Manu

2024-04-04 14:23 UTC, CrackTC requested changes
Hello manuhabitela, first of all, thank you so much for your pull request. I didn't even expect that someone would be interested in contributing to this project 😉.

Back to the topic, I really like your idea of adding this feature to the plugin. IMO test `:` is enough, just a few changes to your code and it will be ready to merge.

2024-04-04 14:23 UTC, CrackTC commented on src/ts.c
> +    char **words = g_strsplit ( pd->prev_input, " ", -1 );
```suggestion
    char **words = g_strsplit ( pd->prev_input, " ", 2 );
```

2024-04-04 14:23 UTC, CrackTC commented on src/ts.c
> +        g_ptr_array_add ( argv, sentenceToTranslate );
```suggestion
        g_ptr_array_add ( argv, words[0] );
        g_ptr_array_add ( argv, words[1] );
```

2024-04-04 14:23 UTC, CrackTC commented on src/ts.c
> +    char **words = g_strsplit ( pd->prev_input, " ", -1 );
We can free this after line 448

2024-04-05 21:55 UTC, manuhabitela commented
Hey, thanks for the feedback, sorry for the low quality code, it's actually my first time writing C haha so really I don't know what I'm doing.

Updated the branch with your input. Thanks!

2024-04-05 22:13 UTC, CrackTC approved these changes
Never mind, tested and it works perfectly. Thank you so much for your contribution! 🎉

2024-04-05 22:13 UTC, merged